spring.application.name=gateway-assignement
server.port=3000


spring.cloud.gateway.routes[0].id=users-route
spring.cloud.gateway.routes[0].uri=http://localhost:3001
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=products-route
spring.cloud.gateway.routes[1].uri=http://localhost:3002
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

